# Generated by Django 4.2.3 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(max_length=150),
        ),
    ]
